<#
.SYNOPSIS
    Regenerates ParticleConverter/Minecraft/ParticleRegistry.Generated.cs.

.DESCRIPTION
    Downloads the particle_type registry dump for every supported Minecraft version from
    misode/mcmeta and encodes, for each particle id, the set of versions it exists in as a bit
    mask over the version order below.

    That order MUST match McVersionProfile.All - the mask bit index is the profile's Index.
    ParticleConverter.Tests guards this with Version_indexes_match_their_position_in_the_list
    and Version_particle_counts_match_the_registry_dumps.

.EXAMPLE
    pwsh tools/gen_registry.ps1
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path $PSScriptRoot -Parent
$dest = Join-Path $repoRoot "ParticleConverter\Minecraft\ParticleRegistry.Generated.cs"

# Oldest -> newest. Index here is the bit position in the availability mask.
$versions = @('1.16.5', '1.20.4', '1.20.6', '1.21', '1.21.4', '1.21.5', '1.21.8', '1.21.9', '1.21.11', '26.1', '26.2')

# Particles whose options this tool knows how to write. Anything absent takes no options.
$optionKind = @{
    'dust'                  = 'Dust'
    'dust_color_transition' = 'DustColorTransition'
    'entity_effect'         = 'ColorArgb'
    'flash'                 = 'ColorArgb'
    'tinted_leaves'         = 'ColorArgb'
    'block'                 = 'BlockState'
    'block_marker'          = 'BlockState'
    'falling_dust'          = 'BlockState'
    'dust_pillar'           = 'BlockState'
    'block_crumble'         = 'BlockState'
    'item'                  = 'Item'
    'sculk_charge'          = 'Raw'
    'shriek'                = 'Raw'
    'vibration'             = 'Raw'
    'trail'                 = 'Raw'
    'geyser'                = 'Raw'
    'geyser_base'           = 'Raw'
    'geyser_plume'          = 'Raw'
    'geyser_poof'           = 'Raw'
}

$sets = @{}
foreach ($v in $versions) {
    $url = "https://raw.githubusercontent.com/misode/mcmeta/$v-registries/particle_type/data.json"
    Write-Host "fetching $v ..."
    $ids = (Invoke-WebRequest -Uri $url).Content | ConvertFrom-Json
    $sets[$v] = [System.Collections.Generic.HashSet[string]]::new([string[]]$ids)
}

$all = [System.Collections.Generic.SortedSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($v in $versions) { foreach ($p in $sets[$v]) { [void]$all.Add($p) } }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//     Generated from the misode/mcmeta particle_type registry dumps.')
[void]$sb.AppendLine('//     Regenerate with tools/gen_registry.ps1 when a new Minecraft version is added.')
[void]$sb.AppendLine('//     Do not edit by hand.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace ParticleConverter.Minecraft')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    public static partial class ParticleRegistry')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Every particle id known to any supported version, with the set of versions it')
[void]$sb.AppendLine('        /// exists in encoded as a bit mask over <see cref="McVersionProfile.All"/> order.')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        private static readonly ParticleDefinition[] Definitions =')
[void]$sb.AppendLine('        {')

foreach ($p in $all) {
    $mask = 0
    for ($i = 0; $i -lt $versions.Count; $i++) {
        if ($sets[$versions[$i]].Contains($p)) { $mask = $mask -bor (1 -shl $i) }
    }
    $kind = if ($optionKind.ContainsKey($p)) { $optionKind[$p] } else { 'None' }
    [void]$sb.AppendLine(('            new ParticleDefinition("{0}", ParticleOptionKind.{1}, 0x{2:X4}),' -f $p, $kind, $mask))
}

[void]$sb.AppendLine('        };')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')

[System.IO.File]::WriteAllText($dest, $sb.ToString())
Write-Host "wrote $dest ($($all.Count) particles across $($versions.Count) versions)"
